---
- hosts: localhost
  tasks:
    - name: Install NVM
      shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash

    - name: Install Node
      shell: source ~/.dotfiles/main.sh && nvm install --lts
