---
- hosts: localhost
  vars:
    apps:
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libssl1.0-dev
      - libsqlite3-dev

  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ apps }}"
      become: True

   - name: Get pyenv installer
      get_url:
        url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
        dest: /tmp/pyenv-installer

    - name: Run pyenv installer
      shell: bash /tmp/pyenv-installer
