---
- hosts: localhost
  vars:
    apps:
      - libncurses5-dev
      - libgdbm-dev
      - libnss3-dev
      - libffi-dev 
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libssl-dev
      - libsqlite3-dev

  tasks:
    - name: Install packages
      apt:
        name: "{{ apps }}"
        state: present
      become: True

    - name: Get pyenv installer
      get_url:
        url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
        dest: /tmp/pyenv-installer

    - name: Run pyenv installer
      shell: bash /tmp/pyenv-installer
